"""
Unit tests for Analyze class
"""
from prose_rhythm.analyze import Analyze

analyze = Analyze()


def test_get_rhythms_elision():
    test_tokens = {'text': [{'contains_abbrev': False,
                             'contains_numeral': False,
                             'plain_text_sentence': 'sī quem habētis dēpōnite',
                             'structured_sentence': [{'index': 0,
                                                      'syllables': [{'accented': True,
                                                                     'elide': (False, None),
                                                                     'index': 0,
                                                                     'long_by_nature': True,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'sī'}],
                                                      'syllables_count': 1,
                                                      'word': 'sī'},
                                                     {'index': 1,
                                                      'syllables': [{'accented': True,
                                                                     'elide': (True, 'strong'),
                                                                     'index': 0,
                                                                     'long_by_nature': False,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'quem'}],
                                                      'syllables_count': 1,
                                                      'word': 'quem'},
                                                     {'index': 2,
                                                      'syllables': [{'accented': False,
                                                                     'elide': (False, None),
                                                                     'index': 0,
                                                                     'long_by_nature': False,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'ha'},
                                                                    {'accented': True,
                                                                     'elide': (False, None),
                                                                     'index': 1,
                                                                     'long_by_nature': True,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'bē'},
                                                                    {'accented': False,
                                                                     'elide': (False, None),
                                                                     'index': 2,
                                                                     'long_by_nature': False,
                                                                     'long_by_position': (True, None),
                                                                     'syllable': 'tis'}],
                                                      'syllables_count': 3,
                                                      'word': 'habētis'},
                                                     {'index': 3,
                                                      'syllables': [{'accented': False,
                                                                     'elide': (False, None),
                                                                     'index': 0,
                                                                     'long_by_nature': True,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'dē'},
                                                                    {'accented': True,
                                                                     'elide': (False, None),
                                                                     'index': 1,
                                                                     'long_by_nature': True,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'pō'},
                                                                    {'accented': False,
                                                                     'elide': (False, None),
                                                                     'index': 2,
                                                                     'long_by_nature': False,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'ni'},
                                                                    {'accented': False,
                                                                     'elide': (False, None),
                                                                     'index': 3,
                                                                     'long_by_nature': False,
                                                                     'long_by_position': (False, None),
                                                                     'syllable': 'te'}],
                                                      'syllables_count': 4,
                                                      'word': 'dēpōnite'}]},
                            {'contains_abbrev': False,
                             'contains_numeral': False,
                             'plain_text_sentence': '',
                             'structured_sentence': []}],
                   'title': 'No Title'}
    correct = [('sī quem habētis dēpōnite', 'uu----ux')]
    assert analyze.get_rhythms(test_tokens) == correct
